"""Cut migration species composite images into individual sprites.

Reads 2x2 grid images generated by ChatGPT, splits into quadrants,
crops each to its opaque content, and saves with proper species names.

Usage:
    python scripts/cut_migration_sprites.py /path/to/migration_species/
"""
import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image

# Batch order must match curation/aquatic/sprite_gen_migration.js exactly
MIGRATION_SPECIES = [
    # Batch 1: Salmon
    "Oncorhynchus nerka", "Oncorhynchus gorbuscha",
    "Oncorhynchus keta", "Salvelinus alpinus",
    # Batch 2: Tuna
    "Thunnus orientalis", "Thunnus maccoyii",
    "Thunnus albacares", "Thunnus alalunga",
    # Batch 3: Tuna + Sharks
    "Katsuwonus pelamis", "Isurus oxyrinchus",
    "Sphyrna lewini", "Lamna nasus",
    # Batch 4: Sharks
    "Galeorhinus galeus", "Notorynchus cepedianus",
    "Squalus acanthias", "Anguilla rostrata",
    # Batch 5: Eels
    "Anguilla japonica", "Anguilla dieffenbachii",
    "Anguilla australis", "Coryphaena hippurus",
    # Batch 6: Big game fish
    "Makaira nigricans", "Megalops atlanticus",
    "Seriola lalandi", "Sardinops sagax",
    # Batch 7: Small pelagics
    "Mallotus villosus", "Trachurus murphyi",
    "Huso huso", "Acipenser oxyrinchus",
    # Batch 8: Sturgeon
    "Acipenser sinensis", "Pangasianodon gigas",
    "Hucho taimen", "Polyodon spathula",
    # Batch 9: Anadromous/amphidromous
    "Morone saxatilis", "Alosa sapidissima",
    "Tenualosa ilisha", "Lates calcarifer",
    # Batch 10: More anadromous
    "Chanos chanos", "Salminus brasiliensis",
    "Tor putitora", "Albula vulpes",
    # Batch 11: Southern hemisphere
    "Dissostichus eleginoides", "Arripis trutta",
    "Arripis georgiana", "Thyrsites atun",
    # Batch 12: Southern continued
    "Hoplostethus atlanticus", "Macruronus novaezelandiae",
    "Genypterus blacodes", "Seriolella brama",
    # Batch 13: Southern continued
    "Callorhinchus milii", "Galaxias maculatus",
    "Micromesistius australis", "Champsocephalus gunnari",
    # Batch 14: Antarctic
    "Notothenia rossii", "Chaenocephalus aceratus",
    "Pleuragramma antarctica", "Electrona carlsbergi",
    # Batch 15: Last one
    "Amblyraja georgiana",
]

OUT_DIR = Path(__file__).resolve().parent.parent / "output" / "aquatic" / "sprites"
ALPHA_THRESHOLD = 30
PADDING = 5


def to_filename(name: str) -> str:
    """Convert species name to sprite filename."""
    return "sp-" + re.sub(r'[^a-z0-9_]', '_', name.lower().strip()).strip('_') + ".png"


def crop_to_content(arr: np.ndarray, padding: int = PADDING) -> np.ndarray:
    """Crop RGBA array to its opaque content bounding box."""
    alpha = arr[:, :, 3]
    opaque = alpha > ALPHA_THRESHOLD
    rows = np.any(opaque, axis=1)
    cols = np.any(opaque, axis=0)

    if not np.any(rows):
        return arr

    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]

    h, w = arr.shape[:2]
    rmin = max(0, rmin - padding)
    cmin = max(0, cmin - padding)
    rmax = min(h - 1, rmax + padding)
    cmax = min(w - 1, cmax + padding)

    return arr[rmin:rmax + 1, cmin:cmax + 1]


def clean_background(arr: np.ndarray) -> np.ndarray:
    """Zero out semi-transparent dark background pixels.

    ChatGPT renders a dark gradient halo around the fish.
    Remove pixels where RGB is very dark and alpha is low.
    """
    result = arr.copy()
    r, g, b, a = result[:,:,0], result[:,:,1], result[:,:,2], result[:,:,3]

    # Dark semi-transparent pixels = background halo
    brightness = r.astype(int) + g.astype(int) + b.astype(int)
    is_dark_halo = (brightness < 120) & (a < 180) & (a > 0)
    result[is_dark_halo, 3] = 0

    return result


def process_composite(img_path: Path, species_names: list[str]):
    """Split a 2x2 composite image and save individual sprites."""
    img = Image.open(img_path).convert("RGBA")
    arr = np.array(img)
    h, w = arr.shape[:2]
    mid_h, mid_w = h // 2, w // 2

    # Quadrants: top-left, top-right, bottom-left, bottom-right
    quadrants = [
        arr[:mid_h, :mid_w],
        arr[:mid_h, mid_w:],
        arr[mid_h:, :mid_w],
        arr[mid_h:, mid_w:],
    ]

    results = []
    for i, name in enumerate(species_names):
        if i >= len(quadrants):
            break

        quad = quadrants[i]
        cleaned = clean_background(quad)
        cropped = crop_to_content(cleaned)

        # Make background fully transparent
        out = Image.fromarray(cropped)
        filename = to_filename(name)
        out_path = OUT_DIR / filename
        out.save(out_path, "PNG")

        results.append((name, filename, cropped.shape[1], cropped.shape[0]))
        print(f"    {name} -> {filename} ({cropped.shape[1]}x{cropped.shape[0]})")

    return results


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/cut_migration_sprites.py /path/to/migration_species/")
        return

    src_dir = Path(sys.argv[1])
    if not src_dir.is_dir():
        print(f"ERROR: {src_dir} is not a directory")
        return

    # Sort images by filename (timestamp order = batch order)
    img_files = sorted(f for f in src_dir.iterdir() if f.suffix.lower() == '.png')
    print(f"Found {len(img_files)} composite images")
    print(f"Expected species: {len(MIGRATION_SPECIES)}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    total_cut = 0
    batch_size = 4

    for img_idx, img_file in enumerate(img_files):
        start = img_idx * batch_size
        end = min(start + batch_size, len(MIGRATION_SPECIES))
        batch_names = MIGRATION_SPECIES[start:end]

        if not batch_names:
            print(f"\n  [{img_idx}] {img_file.name} — no more species to assign, skipping")
            continue

        print(f"\n  [{img_idx}] {img_file.name} — batch {start+1}-{end}")
        results = process_composite(img_file, batch_names)
        total_cut += len(results)

    print(f"\n=== Done ===")
    print(f"  Cut {total_cut} sprites from {len(img_files)} composites")
    print(f"  Output: {OUT_DIR}")


if __name__ == "__main__":
    main()
